export const SET_DEVICE_TOGGLE = "SET_DEVICE_TOGGLE";
export const SET_DIAGNOSIS_TOGGLE = "SET_DIAGNOSIS_TOGGLE";
export const SET_PATIENT = "SET_PATIENT";
export const SET_PATIENT_DEVICE_TOGGLE = "SET_PATIENT_DEVICE_TOGGLE";
export const SET_PATIENT_DIAGNOSIS_TOGGLE = "SET_PATIENT_DIAGNOSIS_TOGGLE";
export const SET_FACILITY_LIBRARY_TOGGLE = "SET_FACILITY_LIBRARY_TOGGLE";
export const SET_DOCUMENT_LIBRARY = "SET_DOCUMENT_LIBRARY";
export const SET_CHECKBOX_FILTERS = "SET_CHECKBOX_FILTERS";
export const SET_PATIENT_FACILITY_LIBRARY_TOGGLE = "SET_PATIENT_FACILITY_LIBRARY_TOGGLE";

export const SET_PATIENT_DEVICES = "SET_PATIENT_DEVICES";
export const SET_PATIENT_DIAGNOSES = "SET_PATIENT_DIAGNOSES";

export const SET_SELECT_ALL_PATIENT_FACILITY_LIBRARY_FORMS =
  "SET_SELECT_ALL_PATIENT_FACILITY_LIBRARY_FORMS";
export const SET_SELECT_ALL_PATIENT_GENERAL_FORMS = "SET_SELECT_ALL_PATIENT_GENERAL_FORMS";
export const SET_SELECT_ALL_PATIENT_DIAGNOSIS = "SET_SELECT_ALL_PATIENT_DIAGNOSIS";
export const SET_PATIENT_FACILITY_FORMS = "SET_PATIENT_FACILITY_FORMS";
