export const RESET_FILTERED_DOCUMENT_LIBRARY = "RESET_FILTERED_DOCUMENT_LIBRARY";
export const SET_ARBITRATION_LIBRARY = "SET_ARBITRATION_LIBRARY";
export const SET_CURRENT_MASTER_ICD_FILENAME = "SET_CURRENT_MASTER_ICD_FILENAME";
export const SET_DOCUMENT_LIBRARY = "SET_DOCUMENT_LIBRARY";
export const SET_FILTERED_DOCUMENT_LIBRARY = "SET_FILTERED_DOCUMENT_LIBRARY";
