export const SET_FACILITIES = "SET_FACILITIES";
export const SET_SELECTED_FACILITY = "SET_SELECTED_FACILITY";
export const RESET = "RESET";
export const SET_FACILITIES_AND_SELECTED_FACILITY = "SET_FACILITIES_AND_SELECTED_FACILITY";
