export enum FeatureId {
  ARBITRATION_REPORTS = 6,
  AUTO_ISO = 24,
  AUTO_ISO_BASELINE = 25,
  AUTO_ISO_ADMISSION = 26,
  SUMMARY_REPORTS = 27,
  AUTO_ISO_QUARTERLY = 29,
  PCC_FEATURE_ID = 28,
  BROADCAST_MESSAGE_ID = 30,
}
